### ISSUE TITLE
Adding text after quotes not working

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/editor#16]
It's currently impossible to add text after a quote in the editor. The only way is to remove the quote from the editor, add text, place the cursor before the text and insert the quote.

**Comment by dtdesign** [comment]
This is a bit of a general issue with non widget block elements as see in ckeditor/ckeditor5#11852.

If you think about it from a purely block level perspective then it makes sense to leave the block by creating a new line. However, this is without a doubt not very intuitive for the user.

I was keep a close eye on the aforementioned issue to see if this is being implemented directly in CKEditor before having to invent it myself. This isn’t a top priority at the moment, this version is still under active development and not suitable for any usage beyond integration tests.
