### ISSUE TITLE
Display problems mobile

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/editor#18]
![Screenshot_20230404-002636](https://user-images.githubusercontent.com/81188/229640640-d1b56bec-cdf1-488d-af63-3f85dee6c82b.png)

**Comment by SoftCreatR** [comment]
@dtdesign The performed changes don't work very well:

![Screenshot_20230422-153552](https://user-images.githubusercontent.com/81188/233788288-9460b252-c432-4297-914a-10d67cd460c2.png)

**Comment by dtdesign** [comment]
Fixed in WoltLab/WCF@94de841ef0b1ac34d0565a7a9ac658cfa554b0f1

**Comment by SoftCreatR** [comment]
@dtdesign While that works, there's another problem. As you can see on the screenshot, it shows the tooltip on mobile, when tapping the menu button. This tooltip hides, what's under it, and makes it unreachable:
