### ISSUE TITLE
Annoying confirmation on page change

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/editor#21]
As soon as you change the contents of the editor, and trying to change the page, but also after submitting a content that is posted on the next page, a confirmation box appears that asks, if you really want to leave the current page.

This also happens, if you put something into the editor box and remove it, before leaving the current page.

![image](https://user-images.githubusercontent.com/81188/230017920-303c1440-a12e-4790-9bfc-24bb6d2d6222.png)

**Comment by dtdesign** [comment]
Related: https://github.com/ckeditor/ckeditor5/issues/6754
