### ISSUE TITLE
Cannot set properties of undefined (setting 'label')  

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/editor#28]
Clicking the arrow button next to the "Insert Image" button yields an error:

```
editorerror.js:90 Uncaught TypeError: Cannot set properties of undefined (setting 'label')
    at dropdownView.on.priority (imageinsertui.js:111:1)
    at DropdownView.fire (emittermixin.js:146:1)
    at DropdownView.set [as isOpen] (observablemixin.js:72:1)
    at SplitButtonView.<anonymous> (dropdownview.js:118:1)
    at SplitButtonView.fire (emittermixin.js:146:1)
    at fireDelegatedEvents (emittermixin.js:425:1)
    at ButtonView.fire (emittermixin.js:165:1)
    at TemplateToBinding.<anonymous> (buttonview.js:91:1)
    at ProxyEmitter.callback (template.js:802:1)
    at ProxyEmitter.fire (emittermixin.js:146:1)
```

![image](https://user-images.githubusercontent.com/81188/230383976-84b5a1a9-43d1-48d2-8f21-ab690595e133.png)

**Comment by TimWolla** [comment]
When providing a stack trace, it would be useful to have the original lines. The JS that is bundled in WoltLab/WCF is outdated anyway, the “Webpack” GitHub Action job builds all commits and creates artifacts that include both the JS as well as a source map: https://github.com/WoltLab/editor/actions/runs/4626614175 (“development_build”).

**Comment by SoftCreatR** [comment]
Oh sorry, didn't see that :D I've updated it.

**Comment by mutec** [comment]
@dtdesign I'm building the editor per "build"-script every time I update the site. I replaced my build by the action's un-minified build, re-generated the core's minified JS. The error remains.

I also tested it when debug mode was enabled:
```
ckeditorerror.js:90 Uncaught TypeError: Cannot set properties of undefined (setting 'label')
    at dropdownView.on.priority (imageinsertui.js:111:1)
    at DropdownView.fire (emittermixin.js:146:1)
    at DropdownView.set [as isOpen] (observablemixin.js:72:1)
    at SplitButtonView.<anonymous> (dropdownview.js:118:1)
    at SplitButtonView.fire (emittermixin.js:146:1)
    at fireDelegatedEvents (emittermixin.js:425:1)
    at ButtonView.fire (emittermixin.js:165:1)
    at TemplateToBinding.<anonymous> (buttonview.js:91:1)
    at ProxyEmitter.callback (template.js:802:1)
    at ProxyEmitter.fire (emittermixin.js:146:1)
rethrowUnexpectedError	@	ckeditorerror.js:90
fire	@	emittermixin.js:176
set	@	observablemixin.js:72
(anonym)	@	dropdownview.js:118
fire	@	emittermixin.js:146
fireDelegatedEvents	@	emittermixin.js:425
fire	@	emittermixin.js:165
(anonym)	@	buttonview.js:91
callback	@	template.js:802
fire	@	emittermixin.js:146
domListener	@	emittermixin.js:208
```
No other JS-errors are logged to the console (I tested it against the conversation package, since it's up to date).
In case you want to check it on your own, we're using the most recent action's build at the moment; Debug-Mode is disabled. The generated core-js (and the non-minified files) is based on 7de7bf099e4f802200a2e82e75b6ea99202edb0b.

**Comment by dtdesign** [comment]
@mutec Can you please look into the source code of the page and find the section that starts with `const features = {`. This list controls the loading or unloading of modules and I need to know the values for `attachment`, `image`, `link` and `media`. Pasting the entire object here does work too.

**Comment by SoftCreatR** [comment]
```
		const features = {
			alignment: true,
			attachment: enableAttachments,
			autosave: element.dataset.autosave || "",
			code: true,
			codeBlock: true,
			heading: true,
			html: true,
			image: true,
			link: true,
			list: true,
			media: true,
			mention: element.dataset.supportMention === "true",
			quoteBlock: true,
			strikethrough: true,
			submitOnEnter: false,
			subscript: true,
			superscript: true,
			spoiler: true,
			table: true,
			underline: true,
		};
```

**Comment by mutec** [comment]
@dtdesign I also added the bbcodes-object.

`<textarea id="text" name="text" class="wysiwygTextarea" data-autosave="com.woltlab.wcf.conversation.messageAdd-121" data-support-mention="true" style="display: none;"></textarea>`

```
		const features = {
			alignment: true,
			attachment: enableAttachments,
			autosave: element.dataset.autosave || "",
			code: true,
			codeBlock: true,
			heading: true,
			html: true,
			image: true,
			link: true,
			list: true,
			media: true,
			mention: element.dataset.supportMention === "true",
			quoteBlock: true,
			strikethrough: true,
			submitOnEnter: false,
			subscript: true,
			superscript: true,
			spoiler: true,
			table: true,
			underline: true,
		};

		const bbcodes = [
							{
					icon: 'cart-shopping;false',
					name: 'product',
					label: 'Produkt',
				},
							{
					icon: 'quote-left;true',
					name: 'q',
					label: 'Inline-Zitat',
				},
					];
```

**Comment by dtdesign** [comment]
I’m sorry, that was my fault. I had the integration enabled in the local branch I was working on and did not notice that it was missing in the main branch.
