### ISSUE TITLE
Deleting words on mobile

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/editor#29]
I'm using Gboard, but i think that doesn't matter.

When writing words, and pressing the "remove" key, usually the whole word gets removed. However, this doesn't work anymore in the new editor. It works for the very first word, but on every other word, it just removes the last letter instead, which is kind of annoying.

**Comment by dtdesign** [comment]
Can you please check if this happens with the official build too: https://ckeditor.com/ckeditor-5/demo/feature-rich/?

**Comment by SoftCreatR** [comment]
Good catch. Seems to be an issue in CKEditor itself...

**Comment by SoftCreatR** [comment]
I might report it, yes. Because it's annoying.

**Comment by SoftCreatR** [comment]
https://github.com/ckeditor/ckeditor5/issues/13850
