### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/editor#35]
Translations work fine so far, but there are at least two of them missing:

- Insert block quote
- Insert spoiler

I guess, these are coming from you, and not from CKEditor?

**Comment by TimWolla** [comment]
> I guess, these are coming from you, and not from CKEditor?

Indeed:

https://github.com/WoltLab/editor/blob/a5d81aadd3e78ddc4c07eed3fb87e99f3a333e21/plugins/ckeditor5-woltlab-spoiler/src/woltlabspoilerediting.ts#L48
