### ISSUE TITLE
Format the editor as an input field

### ISSUE THREAD

**Issue by cls-design** [WoltLab/editor#53]
Shouldn't the editor be formatted like an input field? That somehow doesn't look nice and also not right:

![Bildschirmfoto 2023-05-20 um 12 56 14](https://github.com/WoltLab/editor/assets/1590626/f68d4332-3a96-4fbf-a530-992bcb53ba5e)

So you can see at first glance that you can also write something in there:

![Bildschirmfoto 2023-05-20 um 12 55 47](https://github.com/WoltLab/editor/assets/1590626/11e860ab-fad0-4d97-804f-54e0a0bd3467)

**Comment by dtdesign** [comment]
The editor is intentionally not using the same background color, because unlike input fields the color contrast is important. It should provide an “as close as possible” view that mimics the resulting message.
