### ISSUE TITLE
BBCode-Insert-Buttons misleading

### ISSUE THREAD

**Issue by mutec** [WoltLab/editor#84]
In case the cursor is located in a bbcode-element like the code-block, the BBCode-button handles a property-update, but is not acting as an insert-trigger. However the button is still called "Einfügen" instead of "Übernehmen" or something simmilar.

![image](https://github.com/WoltLab/editor/assets/1749344/b2aec70d-1555-41a2-b86c-cc21edb28ddf)

**Comment by dtdesign** [comment]
Fixed in c84a3ce28ece46212cef305519a163e7b3d83a6a
